### ISSUE TITLE
Error when trying to create account after attempting to edit preference as a guest

### ISSUE THREAD

**Issue by TeeWhyKay** [TeeWhyKay/Chomp#65]
![image](https://user-images.githubusercontent.com/72695565/134794785-5340f4ed-83ea-4266-ba53-cbde50d5ef4a.png)

Error shows up after attempting to create account when trying to edit preference as guest

**Comment by mxng** [comment]
Logging in again as previous user and inputting the join code from landing page will bring them to a form with blank slate.

Inputting details again will cause 2 input from the same user saved.
<img width="1200" alt="Screenshot 2021-09-26 at 4 36 48 PM" src="https://user-images.githubusercontent.com/11084577/134800458-04f83436-f54d-48c2-9a3a-208c489f6b36.png">

One way is to check the current_user 's ID is already existing in the DB, if yes, overwrite it with the new input.

**Comment by TeeWhyKay** [comment]
Closed this issue as guest can no longer click on edit preferences. This issue is probably also caused by the form previously having remote: true on user forms. See branch #96
